# ----------------------------------------------------------------------------------------------------------
# This skript was made by Brian9171
# Reach out to me on discord (brian9171) if you have any questions or want to make any bug reports.
# ----------------------------------------------------------------------------------------------------------

import:
  org.bukkit.util.Vector

on load:
  set {-2dsr-element-vertices::*} to vector(-0.5, -0.5, 0), vector( 0.5, -0.5, 0), vector( 0.5,  0.5, 0), vector(-0.5,  0.5, 0)
  #
  set {-2dsr-base-scale} to vector(1, 0.5, 0) # 
  set {-2dsr-base-center-translation} to vector(-0.0125, -0.061, 0)
  #
  set {-2dsr-pixel-scale-translation} to 0.0025
  set {-2dsr-pixel-scale-scale} to 0.02
  #
  set {-2dsr-screen-scale} to vector(8, 4, 0)
  set {-2dsr-screen-translation} to vector(-0.0125, -0.125, 0)

struct Scene:
  elements: Element structs
  #
  position: location = location(0.5, 4, 0.5, world "world")
  forward: vector
  #
  background_colour: colour # If it is not set, there will be no background.
  #
  scene_scale: vector = vector(1, 1, 0) # scale of the scene
  #
  right: vector
  up: vector
  #
  background: Entity

struct Element:
  position: vector = vector(0, 0, 0)
  pivot: vector = vector(0, 0, 0)
  rotation: vector = vector(0, 0, 0)
  scale: vector = vector(100, 100, 100)
  colour: colour = rgb(255, 255, 255)
  #
  interpolation: integer = 1 # How many ticks of interpolation does this element have?
  #
  entity: Entity
  # corner vertices
  c: vectors
  # axes
  n0: vector
  n1: vector

# Setup the scene!
function setup_scene(scene: Scene struct) :: Scene struct:
  # Set up the axes
  if {_scene}->forward is not set:
    set {_scene}->forward to normalized (vector from yaw (yaw of ({_scene}->position)) and pitch (pitch of ({_scene}->position)))
  #
  set {_scene}->right to normalized (({_scene}->forward) cross vector(0, 1, 0))
  set {_scene}->up to normalized (({_scene}->right) cross ({_scene}->forward))
  # Set yaw / pitch
  set yaw of ({_scene}->position) to yaw of ({_scene}->forward)
  set pitch of ({_scene}->position) to pitch of ({_scene}->forward)
  # Create the background entity
  if {_scene}->background_colour is set:
    spawn text display at ({_scene}->position)
    set {_back} to last spawned entity
    #
    set text of {_back} to " "
    set colour of {_back} to ({_scene}->background_colour)
    #
    set {_scale} to ({_scene}->scene_scale) * {-2dsr-screen-scale}
    #
    set transformation scale of {_back} to {_scale}
    set transformation translation of {_back} to {_scale} * {-2dsr-screen-translation}
    #
    set {_scene}->background to {_back}
  #
  return {_scene}

# Update everything about the element!
function update_element_all(element: Element struct):
  set {_rotation} to {_element}->rotation
  # Calculate world-space corners
  set {_c::*} to {-2dsr-element-vertices::*} transformed using [input * {_element}->scale]
  #
  set {_angle} to (x of {_rotation}) * 57.2957795131
  #
  loop {_c::*}:
    set {_x} to x of (loop-value)
    set {_y} to y of (loop-value)
    set {_nx} to ({_x} * cos({_angle})) - ({_y} * sin({_angle}))
    set {_ny} to ({_x} * sin({_angle})) + ({_y} * cos({_angle}))
    set {_c::%loop-index%} to vector({_nx}, {_ny}, 0) + {_element}->position
  #
  set {_element}->c to {_c::*}
  # Calculate the axes
  set {_n} to normalized ({_c::2} - {_c::1})
  set {_element}->n0 to {_n}
  set {_element}->n1 to normalized vector((y of {_n}) * -1, x of {_n}, 0)

# If you want to update the element's position without changing its rotation.
function update_element_position(element: Element struct, offset: vector):
  set {_element}->c to {_element}->c transformed using [input + {_offset}]

function render_element(element: Element struct, recalculate_orientation: boolean = true):
  # Calculate scale:
  set {_scale} to ({_element}->scale) * {-2dsr-pixel-scale-scale}
  # Check if we need to recalculate orientation
  if {_recalculate_orientation} = true:
    set {_orientation} to ((left rotation of {_element}->entity).identity()).rotationZYX((x of {_element}->rotation), (y of {_element}->rotation), (z of {_element}->rotation))
  else:
    set {_orientation} to left rotation of {_element}->entity
  # Calculate translation
  set {_translation} to ({-2dsr-base-center-translation} * {_scale}).toVector3f()
  set {_translation} to {_translation}.rotate({_orientation})
  set {_translation} to Vector.fromJOML({_translation}) + ({_element}->position) * {-2dsr-pixel-scale-translation}
  # Update:
  set interpolation delay of {_element}->entity to 0 tick
  #
  set colour of {_element}->entity to {_el-a}->colour
  set transformation scale of {_element}->entity to {_scale} * {-2dsr-base-scale}
  #
  if {_recalculate_orientation} = true:
    set left rotation of {_entity} to {_orientation}
  #
  set transformation translation of {_element}->entity to {_translation}

function add_element_to_scene(scene: Scene struct, element: Element struct) :: Element struct:
  #
  update_element_all({_element})
  # Spawn the entity
  set {_slightly-forward} to ({_scene}->forward) * 0.0001
  spawn text display at ({_scene}->position) ~ {_slightly-forward}
  set {_e} to last spawned entity
  #
  set text of {_e} to " "
  set interpolation duration of {_e} to ({_element}->interpolation) * (1 tick)
  #
  set {_element}->entity to {_e}
  #
  render_element({_element})
  # Add the element to the scene's elements
  add {_element} to {_scene}->elements
  #
  return {_element}

function delete_scene(scene: Scene struct):
  delete entity within ({_scene}->background)
  loop {_scene}->elements:
    delete entity within (loop-value)->entity
  #
  delete {_scene}

function delete_element(scene: Scene struct, element: Element struct):
  delete entity within ({_element}->entity)
  remove {_element} from {_scene}->elements
  #
  delete {_element}

function elements_overlap(a: Element struct, b: Element struct) :: boolean:
  # Calculate the axes
  set {_axes::1} to {_a}->n0
  set {_axes::2} to {_a}->n1
  set {_axes::3} to {_b}->n0
  set {_axes::4} to {_b}->n1
  #
  loop {_axes::*}:
    set {_av::*} to project_element(loop-value, {_a})
    set {_bv::*} to project_element(loop-value, {_b})
    #
    if any:
      {_av::2} < {_bv::1}
      {_bv::2} < {_av::1}
    then:
      return false
  #
  return true

function project_element(a: vector, e: Element struct) :: numbers:
  set {_min} to ∞
  set {_max} to -∞
  loop {_e}->c:
    set {_d} to (loop-value) dot {_a}
    set {_min} to min({_d}, {_min})
    set {_max} to max({_d}, {_max})
  #
  return ({_min}, {_max})
